"use client"

import type React from "react"
import { useState, useRef } from "react"
import { useNavigate } from "react-router-dom"
import {
  Box,
  Typography,
  Button,
  TextField,
  Paper,
  Grid,
  IconButton,
  Stepper,
  Step,
  StepLabel,
  Alert,
  CircularProgress,
} from "@mui/material"
import { X, Upload, Plus, ArrowRight, Sparkles } from "lucide-react"
import AuctionDetailsForm from "../components/AuctionDetailsForm"

interface UploadedImage {
  id: string
  file: File
  preview: string
}

const CreateAuction: React.FC = () => {
  const navigate = useNavigate()
  const [activeStep, setActiveStep] = useState(0)
  const [uploadedImages, setUploadedImages] = useState<UploadedImage[]>([])
  const [description, setDescription] = useState("")
  const [isGeneratingDescription, setIsGeneratingDescription] = useState(false)
  const [auctionType, setAuctionType] = useState<"fixed" | "extended" | null>(null)
  const [formValid, setFormValid] = useState(false)
  const [detailsData, setDetailsData] = useState({
    name: "",
    status: "Brand new",
    condition: 50,
    category: "",
  })
  const fileInputRef = useRef<HTMLInputElement>(null)

  const handleFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files) {
      const newFiles = Array.from(event.target.files)

      const newImages = newFiles.map((file) => ({
        id: Math.random().toString(36).substring(2, 9),
        file,
        preview: URL.createObjectURL(file),
      }))

      setUploadedImages([...uploadedImages, ...newImages])
    }
  }

  const handleRemoveImage = (id: string) => {
    const updatedImages = uploadedImages.filter((img) => img.id !== id)
    setUploadedImages(updatedImages)
  }

  const handleAutogenerateDescription = () => {
    setIsGeneratingDescription(true)

    // Simulate AI description generation
    setTimeout(() => {
      const generatedText =
        "This is an automatically generated description based on your uploaded images. " +
        "This item appears to be in excellent condition and would make a great addition to any collection. " +
        "The item shows minimal signs of wear and comes from a smoke-free environment. " +
        "Please review the photos carefully and feel free to ask any questions before bidding."

      setDescription(generatedText)
      setIsGeneratingDescription(false)
    }, 1500)
  }

  const handleContinue = () => {
    if (uploadedImages.length >= 1 && description.trim().length > 0) {
      setActiveStep(1)
    }
  }

  const handleAuctionTypeSelect = (type: "fixed" | "extended") => {
    setAuctionType(type)
  }

  interface DetailsData {
    name: string
    status: string
    condition: number
    category: string
  }

  const handleDetailsChange = (data: DetailsData) => {
    setDetailsData(data)
    validateForm(data)
  }

  const validateForm = (data: DetailsData) => {
    const isValid =
      data.name.trim().length > 0 &&
      data.status.trim().length > 0 &&
      data.category.trim().length > 0 &&
      auctionType !== null

    setFormValid(isValid)
  }

  const handleUploadAuction = () => {
    // In a real app, this would send the auction data to the backend
    console.log("Uploading auction:", {
      images: uploadedImages,
      description,
      auctionType,
      details: detailsData,
    })

    // Navigate back to home page after successful upload
    navigate("/")
  }

  return (
    <Box sx={{ bgcolor: "#333", minHeight: "100vh", pb: 5 }}>
      <Box sx={{ bgcolor: "#000", color: "white", p: 2, mb: 3 }}>
        <Typography variant="h5" fontWeight="bold">
          Creating an auction
        </Typography>
      </Box>

      <Box sx={{ maxWidth: 800, mx: "auto", px: 2 }}>
        <Stepper activeStep={activeStep} sx={{ mb: 4, display: { xs: "none", md: "flex" } }}>
          <Step>
            <StepLabel>Upload & Describe</StepLabel>
          </Step>
          <Step>
            <StepLabel>Set Details</StepLabel>
          </Step>
        </Stepper>

        {activeStep === 0 ? (
          <>
            {/* Step 1: Upload photos and description */}
            <Typography variant="h6" sx={{ color: "white", borderBottom: "1px solid #555", pb: 1, mb: 3 }}>
              Upload photos
            </Typography>

            <Paper sx={{ p: 3, mb: 4, bgcolor: "#444", borderRadius: 3 }}>
              <Box
                sx={{
                  border: "2px dashed #666",
                  borderRadius: 2,
                  p: 3,
                  textAlign: "center",
                  mb: 2,
                }}
              >
                <Box
                  sx={{
                    width: "100%",
                    height: 200,
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    mb: 2,
                  }}
                >
                  <X size={80} color="#999" />
                </Box>

                <input
                  type="file"
                  multiple
                  accept="image/*"
                  style={{ display: "none" }}
                  ref={fileInputRef}
                  onChange={handleFileSelect}
                />

                <Button
                  variant="outlined"
                  onClick={() => fileInputRef.current?.click()}
                  sx={{
                    color: "white",
                    borderColor: "white",
                    mb: 2,
                  }}
                >
                  Choose file
                </Button>

                <Button
                  variant="contained"
                  fullWidth
                  startIcon={<Upload size={18} />}
                  onClick={() => fileInputRef.current?.click()}
                  sx={{
                    bgcolor: "#000",
                    color: "white",
                    "&:hover": {
                      bgcolor: "#222",
                    },
                  }}
                >
                  Upload
                </Button>
              </Box>

              <Typography variant="subtitle1" sx={{ color: "white", mb: 2, mt: 3 }}>
                Uploaded photos
              </Typography>

              <Box sx={{ border: "1px dashed #666", p: 2, borderRadius: 1 }}>
                <Typography variant="body2" sx={{ color: "#ccc", mb: 2, fontSize: "0.8rem" }}>
                  You need to upload AT LEAST 5, and maximum 10 photos of your product. Please try to take the pictures
                  from different angles, so that the product is showcased.
                </Typography>

                <Grid container spacing={2}>
                  {uploadedImages.map((img) => (
                    <Grid item xs={4} key={img.id}>
                      <Box sx={{ position: "relative" }}>
                        <Box
                          component="img"
                          src={img.preview}
                          alt="Uploaded preview"
                          sx={{
                            width: "100%",
                            height: 100,
                            objectFit: "cover",
                            borderRadius: 1,
                          }}
                        />
                        <IconButton
                          size="small"
                          onClick={() => handleRemoveImage(img.id)}
                          sx={{
                            position: "absolute",
                            top: -8,
                            right: -8,
                            bgcolor: "rgba(0,0,0,0.7)",
                            color: "white",
                            "&:hover": {
                              bgcolor: "rgba(0,0,0,0.9)",
                            },
                          }}
                        >
                          <X size={14} />
                        </IconButton>
                      </Box>
                    </Grid>
                  ))}

                  {uploadedImages.length < 10 && (
                    <Grid item xs={4}>
                      <Box
                        sx={{
                          width: "100%",
                          height: 100,
                          border: "1px dashed #666",
                          borderRadius: 1,
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                          cursor: "pointer",
                          "&:hover": {
                            bgcolor: "rgba(255,255,255,0.05)",
                          },
                        }}
                        onClick={() => fileInputRef.current?.click()}
                      >
                        <Plus size={24} color="#999" />
                      </Box>
                    </Grid>
                  )}
                </Grid>

                {uploadedImages.length < 1 && (
                  <Alert severity="warning" sx={{ mt: 2 }}>
                    Please upload at least 1 photo to continue
                  </Alert>
                )}
              </Box>
            </Paper>

            <Typography variant="h6" sx={{ color: "white", borderBottom: "1px solid #555", pb: 1, mb: 3 }}>
              Description
            </Typography>

            <Paper sx={{ p: 3, mb: 4, bgcolor: "#444", borderRadius: 3 }}>
              <Box sx={{ display: "flex", alignItems: "center", mb: 2 }}>
                <Button
                  variant="contained"
                  startIcon={<Sparkles size={18} />}
                  onClick={handleAutogenerateDescription}
                  disabled={isGeneratingDescription || uploadedImages.length === 0}
                  sx={{
                    bgcolor: "#000",
                    color: "white",
                    "&:hover": {
                      bgcolor: "#222",
                    },
                  }}
                >
                  {isGeneratingDescription ? (
                    <CircularProgress size={20} sx={{ color: "white", mr: 1 }} />
                  ) : (
                    "Autogenerate"
                  )}
                </Button>
              </Box>

              <TextField
                multiline
                rows={6}
                fullWidth
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Describe your item in detail..."
                sx={{
                  bgcolor: "#222",
                  borderRadius: 1,
                  "& .MuiOutlinedInput-root": {
                    color: "white",
                  },
                  "& .MuiInputBase-input::placeholder": {
                    color: "#999",
                    opacity: 1,
                  },
                }}
              />

              {description.trim().length === 0 && (
                <Alert severity="warning" sx={{ mt: 2 }}>
                  Please provide a description to continue
                </Alert>
              )}
            </Paper>

            <Box sx={{ display: "flex", justifyContent: "flex-end" }}>
              <Button
                variant="contained"
                endIcon={<ArrowRight size={18} />}
                onClick={handleContinue}
                disabled={uploadedImages.length < 1 || description.trim().length === 0}
                sx={{
                  bgcolor: "white",
                  color: "black",
                  borderRadius: 20,
                  px: 3,
                  "&:hover": {
                    bgcolor: "#eee",
                  },
                  "&.Mui-disabled": {
                    bgcolor: "#555",
                    color: "#999",
                  },
                }}
              >
                Continue
              </Button>
            </Box>
          </>
        ) : (
          <>
            {/* Step 2: Choose auction type and details */}
            <Paper sx={{ p: 4, mb: 4, bgcolor: "#000", color: "white", borderRadius: 3 }}>
              <Typography variant="h5" sx={{ textAlign: "center", mb: 3 }}>
                Choose auction type
              </Typography>

              <Box sx={{ display: "flex", justifyContent: "space-between", gap: 2 }}>
                <Button
                  variant={auctionType === "fixed" ? "contained" : "outlined"}
                  fullWidth
                  onClick={() => handleAuctionTypeSelect("fixed")}
                  sx={{
                    borderRadius: 20,
                    py: 1.5,
                    borderColor: "white",
                    color: auctionType === "fixed" ? "black" : "white",
                    bgcolor: auctionType === "fixed" ? "white" : "transparent",
                    "&:hover": {
                      bgcolor: auctionType === "fixed" ? "#eee" : "rgba(255,255,255,0.1)",
                      borderColor: "white",
                    },
                  }}
                >
                  Fixed time auction
                </Button>

                <Button
                  variant={auctionType === "extended" ? "contained" : "outlined"}
                  fullWidth
                  onClick={() => handleAuctionTypeSelect("extended")}
                  sx={{
                    borderRadius: 20,
                    py: 1.5,
                    borderColor: "white",
                    color: auctionType === "extended" ? "black" : "white",
                    bgcolor: auctionType === "extended" ? "white" : "transparent",
                    "&:hover": {
                      bgcolor: auctionType === "extended" ? "#eee" : "rgba(255,255,255,0.1)",
                      borderColor: "white",
                    },
                  }}
                >
                  Auto extended auction
                </Button>
              </Box>
            </Paper>

            <Typography variant="h6" sx={{ color: "white", borderBottom: "1px solid #555", pb: 1, mb: 3 }}>
              Details
            </Typography>

            <AuctionDetailsForm onChange={handleDetailsChange} />

            <Box sx={{ display: "flex", justifyContent: "flex-end", mt: 4 }}>
              <Button
                variant="contained"
                onClick={handleUploadAuction}
                disabled={!formValid}
                sx={{
                  bgcolor: "white",
                  color: "black",
                  borderRadius: 20,
                  px: 3,
                  "&:hover": {
                    bgcolor: "#eee",
                  },
                  "&.Mui-disabled": {
                    bgcolor: "#555",
                    color: "#999",
                  },
                }}
              >
                Upload auction
              </Button>
            </Box>
          </>
        )}
      </Box>
    </Box>
  )
}

export default CreateAuction

