"use client"

import type React from "react"
import { useState, useRef, useEffect } from "react"
import { useNavigate } from "react-router-dom"
import {
  Box,
  Typography,
  Button,
  TextField,
  Paper,
  Grid,
  IconButton,
  Stepper,
  Step,
  StepLabel,
  Alert,
  CircularProgress,
} from "@mui/material"
import { X, Upload, Plus, ArrowRight, Sparkles } from "lucide-react"

interface UploadedImage {
  id: string
  file: File
  preview: string
}

const UploadAuction: React.FC = () => {
  const navigate = useNavigate()
  const [uploadedImages, setUploadedImages] = useState<UploadedImage[]>([])
  const [description, setDescription] = useState("")
  const [isGeneratingDescription, setIsGeneratingDescription] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)

  // Check session storage for previously uploaded data when coming back from SetDetailsAuction
  useEffect(() => {
    const savedData = sessionStorage.getItem("auctionUploadData")
    if (savedData) {
      try {
        const { description } = JSON.parse(savedData)
        setDescription(description)
        // Note: We can't restore image File objects from session storage
        // In a real app, you would need to handle this differently (e.g., temporary server storage)
      } catch (e) {
        console.error("Error parsing saved auction data", e)
      }
    }
  }, [])

  const handleFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files) {
      const newFiles = Array.from(event.target.files)

      const newImages = newFiles.map((file) => ({
        id: Math.random().toString(36).substring(2, 9),
        file,
        preview: URL.createObjectURL(file),
      }))

      setUploadedImages([...uploadedImages, ...newImages])
    }
  }

  const handleRemoveImage = (id: string) => {
    const updatedImages = uploadedImages.filter((img) => img.id !== id)
    setUploadedImages(updatedImages)
  }

  const handleAutogenerateDescription = () => {
    setIsGeneratingDescription(true)

    // Simulate AI description generation
    setTimeout(() => {
      const generatedText =
        "This is an automatically generated description based on your uploaded images. " +
        "This item appears to be in excellent condition and would make a great addition to any collection. " +
        "The item shows minimal signs of wear and comes from a smoke-free environment. " +
        "Please review the photos carefully and feel free to ask any questions before bidding."

      setDescription(generatedText)
      setIsGeneratingDescription(false)
    }, 1500)
  }

  const handleContinue = () => {
    if (uploadedImages.length >= 1 && description.trim().length > 0) {
      // Save current data to session storage before navigating
      const dataToSave = {
        description,
        imageCount: uploadedImages.length,
      }
      sessionStorage.setItem("auctionUploadData", JSON.stringify(dataToSave))

      // Navigate to the second step
      navigate("/set-details-auction")
    }
  }

  return (
    <Box sx={{ bgcolor: "#333", minHeight: "100vh", pb: 5 }}>
      <Box sx={{ bgcolor: "#000", color: "white", p: 2, mb: 3 }}>
        <Typography variant="h5" fontWeight="bold">
          Creating an auction - Step 1
        </Typography>
      </Box>

      <Box sx={{ maxWidth: 800, mx: "auto", px: 2 }}>
        <Stepper activeStep={0} sx={{ mb: 4, display: { xs: "none", md: "flex" } }}>
          <Step>
            <StepLabel>Upload & Describe</StepLabel>
          </Step>
          <Step>
            <StepLabel>Set Details</StepLabel>
          </Step>
        </Stepper>

        {/* Step 1: Upload photos and description */}
        <Typography variant="h6" sx={{ color: "white", borderBottom: "1px solid #555", pb: 1, mb: 3 }}>
          Upload photos
        </Typography>

        <Paper sx={{ p: 3, mb: 4, bgcolor: "#444", borderRadius: 3 }}>
          <Box
            sx={{
              border: "2px dashed #666",
              borderRadius: 2,
              p: 3,
              textAlign: "center",
              mb: 2,
            }}
          >
            <Box
              sx={{
                width: "100%",
                height: 200,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                mb: 2,
              }}
            >
              <X size={80} color="#999" />
            </Box>

            <input
              type="file"
              multiple
              accept="image/*"
              style={{ display: "none" }}
              ref={fileInputRef}
              onChange={handleFileSelect}
            />

            <Button
              variant="outlined"
              onClick={() => fileInputRef.current?.click()}
              sx={{
                color: "white",
                borderColor: "white",
                mb: 2,
              }}
            >
              Choose file
            </Button>

            <Button
              variant="contained"
              fullWidth
              startIcon={<Upload size={18} />}
              onClick={() => fileInputRef.current?.click()}
              sx={{
                bgcolor: "#000",
                color: "white",
                "&:hover": {
                  bgcolor: "#222",
                },
              }}
            >
              Upload
            </Button>
          </Box>

          <Typography variant="subtitle1" sx={{ color: "white", mb: 2, mt: 3 }}>
            Uploaded photos
          </Typography>

          <Box sx={{ border: "1px dashed #666", p: 2, borderRadius: 1 }}>
            <Typography variant="body2" sx={{ color: "#ccc", mb: 2, fontSize: "0.8rem" }}>
              You need to upload AT LEAST 5, and maximum 10 photos of your product. Please try to take the pictures from
              different angles, so that the product is showcased.
            </Typography>

            <Grid container spacing={2}>
              {uploadedImages.map((img) => (
                <Grid item xs={4} key={img.id}>
                  <Box sx={{ position: "relative" }}>
                    <Box
                      component="img"
                      src={img.preview}
                      alt="Uploaded preview"
                      sx={{
                        width: "100%",
                        height: 100,
                        objectFit: "cover",
                        borderRadius: 1,
                      }}
                    />
                    <IconButton
                      size="small"
                      onClick={() => handleRemoveImage(img.id)}
                      sx={{
                        position: "absolute",
                        top: -8,
                        right: -8,
                        bgcolor: "rgba(0,0,0,0.7)",
                        color: "white",
                        "&:hover": {
                          bgcolor: "rgba(0,0,0,0.9)",
                        },
                      }}
                    >
                      <X size={14} />
                    </IconButton>
                  </Box>
                </Grid>
              ))}

              {uploadedImages.length < 10 && (
                <Grid item xs={4}>
                  <Box
                    sx={{
                      width: "100%",
                      height: 100,
                      border: "1px dashed #666",
                      borderRadius: 1,
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                      cursor: "pointer",
                      "&:hover": {
                        bgcolor: "rgba(255,255,255,0.05)",
                      },
                    }}
                    onClick={() => fileInputRef.current?.click()}
                  >
                    <Plus size={24} color="#999" />
                  </Box>
                </Grid>
              )}
            </Grid>

            {uploadedImages.length < 1 && (
              <Alert severity="warning" sx={{ mt: 2 }}>
                Please upload at least 1 photo to continue
              </Alert>
            )}
          </Box>
        </Paper>

        <Typography variant="h6" sx={{ color: "white", borderBottom: "1px solid #555", pb: 1, mb: 3 }}>
          Description
        </Typography>

        <Paper sx={{ p: 3, mb: 4, bgcolor: "#444", borderRadius: 3 }}>
          <Box sx={{ display: "flex", alignItems: "center", mb: 2 }}>
            <Button
              variant="contained"
              startIcon={<Sparkles size={18} />}
              onClick={handleAutogenerateDescription}
              disabled={isGeneratingDescription || uploadedImages.length === 0}
              sx={{
                bgcolor: "#000",
                color: "white",
                "&:hover": {
                  bgcolor: "#222",
                },
              }}
            >
              {isGeneratingDescription ? <CircularProgress size={20} sx={{ color: "white", mr: 1 }} /> : "Autogenerate"}
            </Button>
          </Box>

          <TextField
            multiline
            rows={6}
            fullWidth
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="Describe your item in detail..."
            sx={{
              bgcolor: "#222",
              borderRadius: 1,
              "& .MuiOutlinedInput-root": {
                color: "white",
              },
              "& .MuiInputBase-input::placeholder": {
                color: "#999",
                opacity: 1,
              },
            }}
          />

          {description.trim().length === 0 && (
            <Alert severity="warning" sx={{ mt: 2 }}>
              Please provide a description to continue
            </Alert>
          )}
        </Paper>

        <Box sx={{ display: "flex", justifyContent: "flex-end" }}>
          <Button
            variant="contained"
            endIcon={<ArrowRight size={18} />}
            onClick={handleContinue}
            disabled={uploadedImages.length < 1 || description.trim().length === 0}
            sx={{
              bgcolor: "white",
              color: "black",
              borderRadius: 20,
              px: 3,
              "&:hover": {
                bgcolor: "#eee",
              },
              "&.Mui-disabled": {
                bgcolor: "#555",
                color: "#999",
              },
            }}
          >
            Continue
          </Button>
        </Box>
      </Box>
    </Box>
  )
}

export default UploadAuction;

