/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.67).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.AuctionBasic;
import io.swagger.model.AuctionCard;
import io.swagger.model.Bid;
import io.swagger.model.InlineResponse2001;
import io.swagger.model.InlineResponse401;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2025-02-28T11:41:36.840793882Z[GMT]")
@Validated
public interface AuctionsApi {

    @Operation(summary = "Get all bids for a specific auction", description = "Returns a list of all bids placed on a specific auction.", tags={ "Auction" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "List of bids for the auction", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Bid.class)))),
        
        @ApiResponse(responseCode = "404", description = "Auction not found") })
    @RequestMapping(value = "/auctions/{auctionId}/bids",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Bid>> auctionsAuctionIdBidsGet(@Parameter(in = ParameterIn.PATH, description = "ID of the auction to retrieve bids for", required=true, schema=@Schema()) @PathVariable("auctionId") String auctionId
);


    @Operation(summary = "Place a bid on an auction", description = "Allows a user to place a bid on a specific auction.", tags={ "Auction" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Bid placed successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Bid.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid bid or auction"),
        
        @ApiResponse(responseCode = "404", description = "Auction not found") })
    @RequestMapping(value = "/auctions/{auctionId}/bids",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Bid> auctionsAuctionIdBidsPost(@Parameter(in = ParameterIn.PATH, description = "ID of the auction to place the bid on", required=true, schema=@Schema()) @PathVariable("auctionId") String auctionId
, @Parameter(in = ParameterIn.DEFAULT, description = "Bid details", schema=@Schema()) @Valid @RequestBody Bid body
);


    @Operation(summary = "Delete auction by ID", description = "Delete a specific auction by its ID.", tags={ "Auction" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Auction deleted successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = InlineResponse2001.class))),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized", content = @Content(mediaType = "application/json", schema = @Schema(implementation = InlineResponse401.class))),
        
        @ApiResponse(responseCode = "404", description = "Auction not found") })
    @RequestMapping(value = "/auctions/{auctionId}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<InlineResponse2001> auctionsAuctionIdDelete(@Parameter(in = ParameterIn.PATH, description = "ID of the auction to update", required=true, schema=@Schema()) @PathVariable("auctionId") String auctionId
);


    @Operation(summary = "Get auction details by ID", description = "Returns basic information about a specific auction.", tags={ "Auction" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Auction details retrieved successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = AuctionBasic.class))),
        
        @ApiResponse(responseCode = "404", description = "Auction not found") })
    @RequestMapping(value = "/auctions/{auctionId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<AuctionBasic> auctionsAuctionIdGet(@Parameter(in = ParameterIn.PATH, description = "ID of the auction to retrieve", required=true, schema=@Schema()) @PathVariable("auctionId") String auctionId
);


    @Operation(summary = "Update auction details by ID", description = "Update the details of a specific auction.", tags={ "Auction" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Auction details updated successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = AuctionBasic.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid data provided"),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized", content = @Content(mediaType = "application/json", schema = @Schema(implementation = InlineResponse401.class))),
        
        @ApiResponse(responseCode = "404", description = "Auction not found") })
    @RequestMapping(value = "/auctions/{auctionId}",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<AuctionBasic> auctionsAuctionIdPut(@Parameter(in = ParameterIn.PATH, description = "ID of the auction to update", required=true, schema=@Schema()) @PathVariable("auctionId") String auctionId
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody AuctionBasic body
);


    @Operation(summary = "Get all auctions with optional filtering", description = "Returns all auctions in AuctionCard format, with optional filtering by status and category.", tags={ "Auction" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "List of auctions", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = AuctionCard.class)))) })
    @RequestMapping(value = "/auctions",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<AuctionCard>> auctionsGet(@Parameter(in = ParameterIn.QUERY, description = "Filter auctions by status (e.g., ACTIVE, CLOSED)" ,schema=@Schema()) @Valid @RequestParam(value = "status", required = false) String status
, @Parameter(in = ParameterIn.QUERY, description = "Filter auctions by category (e.g., Electronics, Vehicles, Furniture). Multiple categories can be provided, separated by commas." ,schema=@Schema()) @Valid @RequestParam(value = "category", required = false) String category
);


    @Operation(summary = "Get auctions the user has bid on", description = "Returns all auctions the authenticated user has placed a bid on.", tags={ "Auction" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "List of auctions the user has bid on", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = AuctionBasic.class)))),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized", content = @Content(mediaType = "application/json", schema = @Schema(implementation = InlineResponse401.class))),
        
        @ApiResponse(responseCode = "404", description = "No auctions found") })
    @RequestMapping(value = "/auctions/my/biddedAuctions",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<AuctionBasic>> auctionsMyBiddedAuctionsGet();


    @Operation(summary = "Get auctions created by the user", description = "Returns all auctions that the authenticated user has created.", tags={ "Auction" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "List of auctions created by the user", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = AuctionBasic.class)))),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized", content = @Content(mediaType = "application/json", schema = @Schema(implementation = InlineResponse401.class))),
        
        @ApiResponse(responseCode = "404", description = "No auctions found") })
    @RequestMapping(value = "/auctions/my/createdAuctions",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<AuctionBasic>> auctionsMyCreatedAuctionsGet();


    @Operation(summary = "Get auctions followed by the user", description = "Returns all auctions the authenticated user is following.", tags={ "Auction" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "List of auctions the user is following", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = AuctionBasic.class)))),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized", content = @Content(mediaType = "application/json", schema = @Schema(implementation = InlineResponse401.class))),
        
        @ApiResponse(responseCode = "404", description = "No auctions found") })
    @RequestMapping(value = "/auctions/my/followedAuctions",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<AuctionBasic>> auctionsMyFollowedAuctionsGet();


    @Operation(summary = "Create a new auction", description = "Creates a new auction for the authenticated user.", tags={ "Auction" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Auction successfully created", content = @Content(mediaType = "application/json", schema = @Schema(implementation = AuctionBasic.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid request data"),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized") })
    @RequestMapping(value = "/auctions",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<AuctionBasic> createAuction(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody AuctionBasic body
);

}

