/**
 * BidVerse
 * This is the BidVerse application's Swagger page.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id The unique identifier of Bids
 * @param itemId The id of the Auctionitem
 * @param userId The id of the User, who made the Bid
 * @param value The money offer in dollars
 * @param timeStamp The time, when the Bid was offered
 * @param isWinning True if this Bid is winning the Auction
 */
data class Bid (

    /* The unique identifier of Bids */
    val id: kotlin.Long? = null,
    /* The id of the Auctionitem */
    val itemId: kotlin.Long? = null,
    /* The id of the User, who made the Bid */
    val userId: kotlin.Long? = null,
    /* The money offer in dollars */
    val value: kotlin.Double? = null,
    /* The time, when the Bid was offered */
    val timeStamp: java.time.LocalDateTime? = null,
    /* True if this Bid is winning the Auction */
    val isWinning: kotlin.Boolean? = null
) {
}