/**
 * BidVerse
 * This is the BidVerse application's Swagger page.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param error 
 */
data class InlineResponse401 (

    val error: kotlin.String? = null
) {
}