/**
 * BidVerse
 * This is the BidVerse application's Swagger page.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param auctionId The Auction part of the WatchId
 * @param userId The User part of the WatchId
 */
data class WatchId (

    /* The Auction part of the WatchId */
    val auctionId: kotlin.Long? = null,
    /* The User part of the WatchId */
    val userId: kotlin.Long? = null
) {
}