/**
* BidVerse
* This is the BidVerse application's Swagger page.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.apis

import com.google.gson.Gson
import io.ktor.application.call
import io.ktor.auth.UserIdPrincipal
import io.ktor.auth.authentication
import io.ktor.auth.authenticate
import io.ktor.auth.OAuthAccessTokenResponse
import io.ktor.auth.OAuthServerSettings
import io.ktor.http.ContentType
import io.ktor.http.HttpStatusCode
import io.ktor.locations.KtorExperimentalLocationsAPI
import io.ktor.locations.delete
import io.ktor.locations.get
import io.ktor.locations.post
import io.ktor.locations.put
import io.ktor.locations.patch
import io.ktor.response.respond
import io.ktor.response.respondText
import io.ktor.routing.Route
import io.ktor.routing.route

import io.swagger.server.Paths
import io.swagger.server.infrastructure.ApiPrincipal


import io.swagger.server.models.AuctionBasic
import io.swagger.server.models.AuctionCard
import io.swagger.server.models.Bid
import io.swagger.server.models.InlineResponse2001
import io.swagger.server.models.InlineResponse401

@KtorExperimentalLocationsAPI
fun Route.AuctionApi() {
    val gson = Gson()
    val empty = mutableMapOf<String, Any?>()
    get<Paths.auctionsAuctionIdBidsGet> {  _: Paths.auctionsAuctionIdBidsGet ->
        val exampleContentType = "application/json"
        val exampleContentString = """[ {
  "timeStamp" : "2000-01-23T04:56:07.000+00:00",
  "itemId" : 6,
  "isWinning" : true,
  "id" : 0,
  "userId" : 1,
  "value" : 5.962133916683182
}, {
  "timeStamp" : "2000-01-23T04:56:07.000+00:00",
  "itemId" : 6,
  "isWinning" : true,
  "id" : 0,
  "userId" : 1,
  "value" : 5.962133916683182
} ]"""
        
        when(exampleContentType) {
            "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
            "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
            else -> call.respondText(exampleContentString)
        }    }
    post<Paths.auctionsAuctionIdBidsPost> {  _: Paths.auctionsAuctionIdBidsPost ->
        val exampleContentType = "application/json"
        val exampleContentString = """{
  "timeStamp" : "2000-01-23T04:56:07.000+00:00",
  "itemId" : 6,
  "isWinning" : true,
  "id" : 0,
  "userId" : 1,
  "value" : 5.962133916683182
}"""
        
        when(exampleContentType) {
            "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
            "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
            else -> call.respondText(exampleContentString)
        }    }
    delete<Paths.auctionsAuctionIdDelete> {  _: Paths.auctionsAuctionIdDelete ->
        val exampleContentType = "application/json"
        val exampleContentString = """{
  "message" : "Auction successfully deleted."
}"""
        
        when(exampleContentType) {
            "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
            "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
            else -> call.respondText(exampleContentString)
        }    }
    get<Paths.auctionsAuctionIdGet> {  _: Paths.auctionsAuctionIdGet ->
        val exampleContentType = "application/json"
        val exampleContentString = """{
  "expiredDate" : "2000-01-23T04:56:07.000+00:00",
  "description" : "description",
  "itemState" : "itemState",
  "type" : "type",
  "userId" : 6,
  "tags" : "tags",
  "itemName" : "itemName",
  "lastBid" : 5.637376656633329,
  "minStep" : 2,
  "id" : 0,
  "extraTime" : "2000-01-23T04:56:07.000+00:00",
  "minimumPrice" : 5.962133916683182,
  "categoryId" : 1,
  "status" : "status",
  "createDate" : "2000-01-23T04:56:07.000+00:00"
}"""
        
        when(exampleContentType) {
            "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
            "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
            else -> call.respondText(exampleContentString)
        }    }
    put<Paths.auctionsAuctionIdPut> {  _: Paths.auctionsAuctionIdPut ->
        val exampleContentType = "application/json"
        val exampleContentString = """{
  "expiredDate" : "2000-01-23T04:56:07.000+00:00",
  "description" : "description",
  "itemState" : "itemState",
  "type" : "type",
  "userId" : 6,
  "tags" : "tags",
  "itemName" : "itemName",
  "lastBid" : 5.637376656633329,
  "minStep" : 2,
  "id" : 0,
  "extraTime" : "2000-01-23T04:56:07.000+00:00",
  "minimumPrice" : 5.962133916683182,
  "categoryId" : 1,
  "status" : "status",
  "createDate" : "2000-01-23T04:56:07.000+00:00"
}"""
        
        when(exampleContentType) {
            "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
            "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
            else -> call.respondText(exampleContentString)
        }    }
    get<Paths.auctionsGet> {  _: Paths.auctionsGet ->
        val exampleContentType = "application/json"
        val exampleContentString = """[ {
  "itemName" : "itemName",
  "lastBid" : 6.027456183070403,
  "expiredDate" : "2000-01-23T04:56:07.000+00:00",
  "id" : 0,
  "createDate" : "2000-01-23T04:56:07.000+00:00"
}, {
  "itemName" : "itemName",
  "lastBid" : 6.027456183070403,
  "expiredDate" : "2000-01-23T04:56:07.000+00:00",
  "id" : 0,
  "createDate" : "2000-01-23T04:56:07.000+00:00"
} ]"""
        
        when(exampleContentType) {
            "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
            "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
            else -> call.respondText(exampleContentString)
        }    }
    get<Paths.auctionsMyBiddedAuctionsGet> {  _: Paths.auctionsMyBiddedAuctionsGet ->
        val exampleContentType = "application/json"
        val exampleContentString = """[ {
  "expiredDate" : "2000-01-23T04:56:07.000+00:00",
  "description" : "description",
  "itemState" : "itemState",
  "type" : "type",
  "userId" : 6,
  "tags" : "tags",
  "itemName" : "itemName",
  "lastBid" : 5.637376656633329,
  "minStep" : 2,
  "id" : 0,
  "extraTime" : "2000-01-23T04:56:07.000+00:00",
  "minimumPrice" : 5.962133916683182,
  "categoryId" : 1,
  "status" : "status",
  "createDate" : "2000-01-23T04:56:07.000+00:00"
}, {
  "expiredDate" : "2000-01-23T04:56:07.000+00:00",
  "description" : "description",
  "itemState" : "itemState",
  "type" : "type",
  "userId" : 6,
  "tags" : "tags",
  "itemName" : "itemName",
  "lastBid" : 5.637376656633329,
  "minStep" : 2,
  "id" : 0,
  "extraTime" : "2000-01-23T04:56:07.000+00:00",
  "minimumPrice" : 5.962133916683182,
  "categoryId" : 1,
  "status" : "status",
  "createDate" : "2000-01-23T04:56:07.000+00:00"
} ]"""
        
        when(exampleContentType) {
            "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
            "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
            else -> call.respondText(exampleContentString)
        }    }
    get<Paths.auctionsMyCreatedAuctionsGet> {  _: Paths.auctionsMyCreatedAuctionsGet ->
        val exampleContentType = "application/json"
        val exampleContentString = """[ {
  "expiredDate" : "2000-01-23T04:56:07.000+00:00",
  "description" : "description",
  "itemState" : "itemState",
  "type" : "type",
  "userId" : 6,
  "tags" : "tags",
  "itemName" : "itemName",
  "lastBid" : 5.637376656633329,
  "minStep" : 2,
  "id" : 0,
  "extraTime" : "2000-01-23T04:56:07.000+00:00",
  "minimumPrice" : 5.962133916683182,
  "categoryId" : 1,
  "status" : "status",
  "createDate" : "2000-01-23T04:56:07.000+00:00"
}, {
  "expiredDate" : "2000-01-23T04:56:07.000+00:00",
  "description" : "description",
  "itemState" : "itemState",
  "type" : "type",
  "userId" : 6,
  "tags" : "tags",
  "itemName" : "itemName",
  "lastBid" : 5.637376656633329,
  "minStep" : 2,
  "id" : 0,
  "extraTime" : "2000-01-23T04:56:07.000+00:00",
  "minimumPrice" : 5.962133916683182,
  "categoryId" : 1,
  "status" : "status",
  "createDate" : "2000-01-23T04:56:07.000+00:00"
} ]"""
        
        when(exampleContentType) {
            "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
            "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
            else -> call.respondText(exampleContentString)
        }    }
    get<Paths.auctionsMyFollowedAuctionsGet> {  _: Paths.auctionsMyFollowedAuctionsGet ->
        val exampleContentType = "application/json"
        val exampleContentString = """[ {
  "expiredDate" : "2000-01-23T04:56:07.000+00:00",
  "description" : "description",
  "itemState" : "itemState",
  "type" : "type",
  "userId" : 6,
  "tags" : "tags",
  "itemName" : "itemName",
  "lastBid" : 5.637376656633329,
  "minStep" : 2,
  "id" : 0,
  "extraTime" : "2000-01-23T04:56:07.000+00:00",
  "minimumPrice" : 5.962133916683182,
  "categoryId" : 1,
  "status" : "status",
  "createDate" : "2000-01-23T04:56:07.000+00:00"
}, {
  "expiredDate" : "2000-01-23T04:56:07.000+00:00",
  "description" : "description",
  "itemState" : "itemState",
  "type" : "type",
  "userId" : 6,
  "tags" : "tags",
  "itemName" : "itemName",
  "lastBid" : 5.637376656633329,
  "minStep" : 2,
  "id" : 0,
  "extraTime" : "2000-01-23T04:56:07.000+00:00",
  "minimumPrice" : 5.962133916683182,
  "categoryId" : 1,
  "status" : "status",
  "createDate" : "2000-01-23T04:56:07.000+00:00"
} ]"""
        
        when(exampleContentType) {
            "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
            "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
            else -> call.respondText(exampleContentString)
        }    }
    post<Paths.createAuction> {  _: Paths.createAuction ->
        val exampleContentType = "application/json"
        val exampleContentString = """{
  "expiredDate" : "2000-01-23T04:56:07.000+00:00",
  "description" : "description",
  "itemState" : "itemState",
  "type" : "type",
  "userId" : 6,
  "tags" : "tags",
  "itemName" : "itemName",
  "lastBid" : 5.637376656633329,
  "minStep" : 2,
  "id" : 0,
  "extraTime" : "2000-01-23T04:56:07.000+00:00",
  "minimumPrice" : 5.962133916683182,
  "categoryId" : 1,
  "status" : "status",
  "createDate" : "2000-01-23T04:56:07.000+00:00"
}"""
        
        when(exampleContentType) {
            "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
            "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
            else -> call.respondText(exampleContentString)
        }    }
}
