/**
* BidVerse
* This is the BidVerse application's Swagger page.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server

import io.ktor.application.ApplicationCall
import io.ktor.http.HttpMethod
import io.ktor.locations.handle
import io.ktor.locations.location
import io.ktor.locations.Location
import io.ktor.util.pipeline.PipelineContext
import io.ktor.routing.Route
import io.ktor.routing.method
import io.swagger.server.models.*;


// NOTE: ktor-location@0.9.0 is missing extension for Route.delete. This includes it.
inline fun <reified T : Any> Route.delete(noinline body: suspend PipelineContext<Unit, ApplicationCall>.(T) -> Unit): Route {
    return location(T::class) {
        method(HttpMethod.Delete) {
            handle(body)
        }
    }
}

object Paths {
    /**
     * Get all bids for a specific auction
     * Returns a list of all bids placed on a specific auction.
     * @param auctionId ID of the auction to retrieve bids for 
     */
    @Location("/auctions/{auctionId}/bids") class auctionsAuctionIdBidsGet(val auctionId: kotlin.String)

    /**
     * Place a bid on an auction
     * Allows a user to place a bid on a specific auction.
     * @param auctionId ID of the auction to place the bid on 
     * @param body Bid details (optional)
     */
    @Location("/auctions/{auctionId}/bids") class auctionsAuctionIdBidsPost(val auctionId: kotlin.String, val body: Bid)

    /**
     * Delete auction by ID
     * Delete a specific auction by its ID.
     * @param auctionId ID of the auction to update 
     */
    @Location("/auctions/{auctionId}") class auctionsAuctionIdDelete(val auctionId: kotlin.String)

    /**
     * Get auction details by ID
     * Returns basic information about a specific auction.
     * @param auctionId ID of the auction to retrieve 
     */
    @Location("/auctions/{auctionId}") class auctionsAuctionIdGet(val auctionId: kotlin.String)

    /**
     * Update auction details by ID
     * Update the details of a specific auction.
     * @param body  
     * @param auctionId ID of the auction to update 
     */
    @Location("/auctions/{auctionId}") class auctionsAuctionIdPut(val body: AuctionBasic, val auctionId: kotlin.String)

    /**
     * Get all auctions with optional filtering
     * Returns all auctions in AuctionCard format, with optional filtering by status and category.
     * @param status Filter auctions by status (e.g., ACTIVE, CLOSED) (optional)
     * @param category Filter auctions by category (e.g., Electronics, Vehicles, Furniture). Multiple categories can be provided, separated by commas. (optional)
     */
    @Location("/auctions") class auctionsGet(val status: kotlin.String, val category: kotlin.String)

    /**
     * Get auctions the user has bid on
     * Returns all auctions the authenticated user has placed a bid on.
     */
    @Location("/auctions/my/biddedAuctions") class auctionsMyBiddedAuctionsGet()

    /**
     * Get auctions created by the user
     * Returns all auctions that the authenticated user has created.
     */
    @Location("/auctions/my/createdAuctions") class auctionsMyCreatedAuctionsGet()

    /**
     * Get auctions followed by the user
     * Returns all auctions the authenticated user is following.
     */
    @Location("/auctions/my/followedAuctions") class auctionsMyFollowedAuctionsGet()

    /**
     * Create a new auction
     * Creates a new auction for the authenticated user.
     * @param body  
     */
    @Location("/auctions") class createAuction(val body: AuctionBasic)

    /**
     * Get all categories
     * Returns a list of all available categories.
     */
    @Location("/categories") class categoriesGet()

    /**
     * Create a new user
     * Registers a new user in the system.
     * @param body  
     */
    @Location("/users/register") class createUser(val body: UserCredentials)

    /**
     * Delete a user
     * Removes a user from the system.
     */
    @Location("/users/me") class deleteUser()

    /**
     * Update a user&#x27;s email and phone number
     * Allows updating only the email address and phone number of a user.
     * @param body  
     */
    @Location("/users/me") class updateUserContact(val body: UserBasic)

    /**
     * User login
     * Validates a username and password.
     * @param body  
     */
    @Location("/users/login") class usersLoginPost(val body: UserCredentials)

    /**
     * Get basic user profile (excluding bids, auctions, watches)
     * 
     */
    @Location("/users/me") class usersMeGet()

}
