/**
* BidVerse
* This is the BidVerse application's Swagger page.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models


/**
 * 
 * @param id The unique identifier of Auctions
 * @param userId The user who created the Auction
 * @param categoryId The category of the Auction
 * @param itemName Name of the Auction item
 * @param minimumPrice Minimum selling price of the item
 * @param status Current status of the Auction (e.g., active, closed)
 * @param createDate Date and time when the Auction was created
 * @param expiredDate Date and time when the Auction expires
 * @param lastBid Latest Bid amount, if any
 * @param description Detailed description of the item
 * @param type Type of the Auction (e.g., timed, restarting)
 * @param extraTime Extra time added to the auction if it's a restarting one
 * @param itemState State of the item (e.g., new, used)
 * @param tags Keywords associated with the Auction item
 * @param minStep Minimum increment step for Bids
 */
data class AuctionBasic (

    /* The unique identifier of Auctions */
    val id: kotlin.Long? = null,
    /* The user who created the Auction */
    val userId: kotlin.Long? = null,
    /* The category of the Auction */
    val categoryId: kotlin.Long? = null,
    /* Name of the Auction item */
    val itemName: kotlin.String? = null,
    /* Minimum selling price of the item */
    val minimumPrice: kotlin.Double? = null,
    /* Current status of the Auction (e.g., active, closed) */
    val status: kotlin.String? = null,
    /* Date and time when the Auction was created */
    val createDate: java.time.LocalDateTime? = null,
    /* Date and time when the Auction expires */
    val expiredDate: java.time.LocalDateTime? = null,
    /* Latest Bid amount, if any */
    val lastBid: kotlin.Double? = null,
    /* Detailed description of the item */
    val description: kotlin.String? = null,
    /* Type of the Auction (e.g., timed, restarting) */
    val type: kotlin.String? = null,
    /* Extra time added to the auction if it's a restarting one */
    val extraTime: java.time.LocalDateTime? = null,
    /* State of the item (e.g., new, used) */
    val itemState: kotlin.String? = null,
    /* Keywords associated with the Auction item */
    val tags: kotlin.String? = null,
    /* Minimum increment step for Bids */
    val minStep: kotlin.Int? = null
) {
}
