/**
* BidVerse
* This is the BidVerse application's Swagger page.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models


/**
 * 
 * @param id The unique identifier of Auctions
 * @param itemName Name of the Auction item
 * @param createDate Date and time when the Auction was created
 * @param expiredDate Date and time when the Auction expires
 * @param lastBid Latest Bid amount, if any
 */
data class AuctionCard (

    /* The unique identifier of Auctions */
    val id: kotlin.Long? = null,
    /* Name of the Auction item */
    val itemName: kotlin.String? = null,
    /* Date and time when the Auction was created */
    val createDate: java.time.LocalDateTime? = null,
    /* Date and time when the Auction expires */
    val expiredDate: java.time.LocalDateTime? = null,
    /* Latest Bid amount, if any */
    val lastBid: kotlin.Double? = null
) {
}
