/**
* BidVerse
* This is the BidVerse application's Swagger page.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models

import io.swagger.server.models.Auction

/**
 * 
 * @param id The unique identifier of Categories
 * @param auctions 
 * @param categoryName The name of the Category
 */
data class Category (

    /* The unique identifier of Categories */
    val id: kotlin.Long? = null,
    val auctions: kotlin.Array<Auction>? = null,
    /* The name of the Category */
    val categoryName: kotlin.String? = null
) {
}
