/**
* BidVerse
* This is the BidVerse application's Swagger page.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models

import io.swagger.server.models.Auction
import io.swagger.server.models.Bid
import io.swagger.server.models.Watch

/**
 * 
 * @param id The unique identifier of Users
 * @param auctions List of Auctions, the User is taking part in
 * @param bids List of Bids the User has offered
 * @param watches List of Auctions watched by the User
 * @param userName The name of the User
 * @param passwordHash The password of the User
 * @param emailAddress The email of the User
 * @param phoneNumber The phone number of the User
 */
data class User (

    /* The unique identifier of Users */
    val id: kotlin.Long? = null,
    /* List of Auctions, the User is taking part in */
    val auctions: kotlin.Array<Auction>? = null,
    /* List of Bids the User has offered */
    val bids: kotlin.Array<Bid>? = null,
    /* List of Auctions watched by the User */
    val watches: kotlin.Array<Watch>? = null,
    /* The name of the User */
    val userName: kotlin.String? = null,
    /* The password of the User */
    val passwordHash: kotlin.String? = null,
    /* The email of the User */
    val emailAddress: kotlin.String? = null,
    /* The phone number of the User */
    val phoneNumber: kotlin.String? = null
) {
}
