/**
* BidVerse
* This is the BidVerse application's Swagger page.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models


/**
 * 
 * @param id 
 * @param userName 
 * @param emailAddress 
 * @param phoneNumber 
 */
data class UserBasic (

    val id: kotlin.Long? = null,
    val userName: kotlin.String? = null,
    val emailAddress: kotlin.String? = null,
    val phoneNumber: kotlin.String? = null
) {
}
