/**
* BidVerse
* This is the BidVerse application's Swagger page.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models


/**
 * 
 * @param userName 
 * @param passwordHash 
 */
data class UserCredentials (

    val userName: kotlin.String? = null,
    val passwordHash: kotlin.String? = null
) {
}
