/**
* BidVerse
* This is the BidVerse application's Swagger page.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models

import io.swagger.server.models.WatchId

/**
 * 
 * @param id 
 * @param auctionId The Auctions that are being watched by the User
 * @param userId The Users watching the Auction
 */
data class Watch (

    val id: WatchId? = null,
    /* The Auctions that are being watched by the User */
    val auctionId: kotlin.Long? = null,
    /* The Users watching the Auction */
    val userId: kotlin.Long? = null
) {
}
