/**
 * BidVerse
 * This is the BidVerse application's Swagger page.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import io.swagger.client.models.AuctionBasic
import io.swagger.client.models.AuctionCard
import io.swagger.client.models.Bid
import io.swagger.client.models.InlineResponse2001
import io.swagger.client.models.InlineResponse401

import io.swagger.client.infrastructure.*

class AuctionApi(basePath: kotlin.String = "https://localhost:8081") : ApiClient(basePath) {

    /**
     * Get all bids for a specific auction
     * Returns a list of all bids placed on a specific auction.
     * @param auctionId ID of the auction to retrieve bids for 
     * @return kotlin.Array<Bid>
     */
    @Suppress("UNCHECKED_CAST")
    fun auctionsAuctionIdBidsGet(auctionId: kotlin.String): kotlin.Array<Bid> {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/auctions/{auctionId}/bids".replace("{" + "auctionId" + "}", "$auctionId")
        )
        val response = request<kotlin.Array<Bid>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<Bid>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Place a bid on an auction
     * Allows a user to place a bid on a specific auction.
     * @param auctionId ID of the auction to place the bid on 
     * @param body Bid details (optional)
     * @return Bid
     */
    @Suppress("UNCHECKED_CAST")
    fun auctionsAuctionIdBidsPost(auctionId: kotlin.String, body: Bid? = null): Bid {
        val localVariableBody: kotlin.Any? = body
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/auctions/{auctionId}/bids".replace("{" + "auctionId" + "}", "$auctionId")
        )
        val response = request<Bid>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as Bid
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Delete auction by ID
     * Delete a specific auction by its ID.
     * @param auctionId ID of the auction to update 
     * @return InlineResponse2001
     */
    @Suppress("UNCHECKED_CAST")
    fun auctionsAuctionIdDelete(auctionId: kotlin.String): InlineResponse2001 {
        val localVariableConfig = RequestConfig(
                RequestMethod.DELETE,
                "/auctions/{auctionId}".replace("{" + "auctionId" + "}", "$auctionId")
        )
        val response = request<InlineResponse2001>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as InlineResponse2001
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Get auction details by ID
     * Returns basic information about a specific auction.
     * @param auctionId ID of the auction to retrieve 
     * @return AuctionBasic
     */
    @Suppress("UNCHECKED_CAST")
    fun auctionsAuctionIdGet(auctionId: kotlin.String): AuctionBasic {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/auctions/{auctionId}".replace("{" + "auctionId" + "}", "$auctionId")
        )
        val response = request<AuctionBasic>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as AuctionBasic
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Update auction details by ID
     * Update the details of a specific auction.
     * @param body  
     * @param auctionId ID of the auction to update 
     * @return AuctionBasic
     */
    @Suppress("UNCHECKED_CAST")
    fun auctionsAuctionIdPut(body: AuctionBasic, auctionId: kotlin.String): AuctionBasic {
        val localVariableBody: kotlin.Any? = body
        val localVariableConfig = RequestConfig(
                RequestMethod.PUT,
                "/auctions/{auctionId}".replace("{" + "auctionId" + "}", "$auctionId")
        )
        val response = request<AuctionBasic>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as AuctionBasic
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Get all auctions with optional filtering
     * Returns all auctions in AuctionCard format, with optional filtering by status and category.
     * @param status Filter auctions by status (e.g., ACTIVE, CLOSED) (optional)
     * @param category Filter auctions by category (e.g., Electronics, Vehicles, Furniture). Multiple categories can be provided, separated by commas. (optional)
     * @return kotlin.Array<AuctionCard>
     */
    @Suppress("UNCHECKED_CAST")
    fun auctionsGet(status: kotlin.String? = null, category: kotlin.String? = null): kotlin.Array<AuctionCard> {
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>().apply {
            if (status != null) {
                put("status", listOf(status.toString()))
            }
            if (category != null) {
                put("category", listOf(category.toString()))
            }
        }
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/auctions", query = localVariableQuery
        )
        val response = request<kotlin.Array<AuctionCard>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<AuctionCard>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Get auctions the user has bid on
     * Returns all auctions the authenticated user has placed a bid on.
     * @return kotlin.Array<AuctionBasic>
     */
    @Suppress("UNCHECKED_CAST")
    fun auctionsMyBiddedAuctionsGet(): kotlin.Array<AuctionBasic> {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/auctions/my/biddedAuctions"
        )
        val response = request<kotlin.Array<AuctionBasic>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<AuctionBasic>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Get auctions created by the user
     * Returns all auctions that the authenticated user has created.
     * @return kotlin.Array<AuctionBasic>
     */
    @Suppress("UNCHECKED_CAST")
    fun auctionsMyCreatedAuctionsGet(): kotlin.Array<AuctionBasic> {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/auctions/my/createdAuctions"
        )
        val response = request<kotlin.Array<AuctionBasic>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<AuctionBasic>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Get auctions followed by the user
     * Returns all auctions the authenticated user is following.
     * @return kotlin.Array<AuctionBasic>
     */
    @Suppress("UNCHECKED_CAST")
    fun auctionsMyFollowedAuctionsGet(): kotlin.Array<AuctionBasic> {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/auctions/my/followedAuctions"
        )
        val response = request<kotlin.Array<AuctionBasic>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<AuctionBasic>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Create a new auction
     * Creates a new auction for the authenticated user.
     * @param body  
     * @return AuctionBasic
     */
    @Suppress("UNCHECKED_CAST")
    fun createAuction(body: AuctionBasic): AuctionBasic {
        val localVariableBody: kotlin.Any? = body
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/auctions"
        )
        val response = request<AuctionBasic>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as AuctionBasic
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
