/**
 * BidVerse
 * This is the BidVerse application's Swagger page.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import io.swagger.client.models.Category

import io.swagger.client.infrastructure.*

class CategoryApi(basePath: kotlin.String = "https://localhost:8081") : ApiClient(basePath) {

    /**
     * Get all categories
     * Returns a list of all available categories.
     * @return kotlin.Array<Category>
     */
    @Suppress("UNCHECKED_CAST")
    fun categoriesGet(): kotlin.Array<Category> {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/categories"
        )
        val response = request<kotlin.Array<Category>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<Category>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
