/**
 * BidVerse
 * This is the BidVerse application's Swagger page.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import io.swagger.client.models.InlineResponse200
import io.swagger.client.models.UserBasic
import io.swagger.client.models.UserCredentials

import io.swagger.client.infrastructure.*

class UserApi(basePath: kotlin.String = "https://localhost:8081") : ApiClient(basePath) {

    /**
     * Create a new user
     * Registers a new user in the system.
     * @param body  
     * @return UserBasic
     */
    @Suppress("UNCHECKED_CAST")
    fun createUser(body: UserCredentials): UserBasic {
        val localVariableBody: kotlin.Any? = body
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/users/register"
        )
        val response = request<UserBasic>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as UserBasic
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Delete a user
     * Removes a user from the system.
     * @return void
     */
    fun deleteUser(): Unit {
        val localVariableConfig = RequestConfig(
                RequestMethod.DELETE,
                "/users/me"
        )
        val response = request<Any?>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Update a user&#x27;s email and phone number
     * Allows updating only the email address and phone number of a user.
     * @param body  
     * @return UserBasic
     */
    @Suppress("UNCHECKED_CAST")
    fun updateUserContact(body: UserBasic): UserBasic {
        val localVariableBody: kotlin.Any? = body
        val localVariableConfig = RequestConfig(
                RequestMethod.PUT,
                "/users/me"
        )
        val response = request<UserBasic>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as UserBasic
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * User login
     * Validates a username and password.
     * @param body  
     * @return InlineResponse200
     */
    @Suppress("UNCHECKED_CAST")
    fun usersLoginPost(body: UserCredentials): InlineResponse200 {
        val localVariableBody: kotlin.Any? = body
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/users/login"
        )
        val response = request<InlineResponse200>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as InlineResponse200
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Get basic user profile (excluding bids, auctions, watches)
     * 
     * @return UserBasic
     */
    @Suppress("UNCHECKED_CAST")
    fun usersMeGet(): UserBasic {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/users/me"
        )
        val response = request<UserBasic>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as UserBasic
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
